#include "stm32f0xx_hal_gpio.h"

#define MUX1_PORT GPIOA
#define MUX2_PORT GPIOA
#define MUX3_PORT GPIOA
#define MUX4_PORT GPIOA

#define MUX1_PIN GPIO_PIN_1
#define MUX2_PIN GPIO_PIN_2
#define MUX3_PIN GPIO_PIN_3
#define MUX4_PIN GPIO_PIN_4



#define SEGMENT_PORT GPIOB

#define SEGMENT_G_PIN GPIO_PIN_3
#define SEGMENT_F_PIN GPIO_PIN_4
#define SEGMENT_A_PIN GPIO_PIN_5
#define SEGMENT_B_PIN GPIO_PIN_6
#define SEGMENT_C_PIN GPIO_PIN_7
#define SEGMENT_D_PIN GPIO_PIN_8
#define SEGMENT_E_PIN GPIO_PIN_9


#define LED_DOT_PORT GPIOA

#define LED_DOT1_PIN GPIO_PIN_5
#define LED_DOT2_PIN GPIO_PIN_6


#define BUTTON_PORT GPIOB

#define BUTTON_MIN_PIN GPIO_PIN_11
#define BUTTON_HOUR_PIN GPIO_PIN_10

